### ISSUE TITLE
sponsors component and page

### ISSUE THREAD

**Issue by Jehfkemsy** [UPE-FIU/Mobile-ShellHacks#4]
hey so this sprint you'll be implementing the sponsors template/component and the page that dynamically populates using a list of the sponsors.... please do some research before our meeting next week

**Comment by RedJediZ** [comment]
You got it Jehf! I'll do some research on it for the next meeting so we can discuss it.

**Comment by Jehfkemsy** [comment]
@pa Please create a pull request of your code so  @jclement92 can link the Popup

**Comment by Jehfkemsy** [comment]
Also @RedJediZ use a JSON file as data source for your Flatlist and be sure to read about sectionList here https://facebook.github.io/react-native/docs/sectionlist.html

**Comment by Jehfkemsy** [comment]
@RedJediZ we need keys for the flatlist items
you can read more here : https://stackoverflow.com/questions/44545148/basic-flatlist-code-throws-warning-react-native

**Comment by RedJediZ** [comment]
Alright no problem. I’ll work on adding the keys
